### ISSUE TITLE
wish: support HTTP 429 and other error conditions

### ISSUE THREAD

**Issue by markstos** [Zooz/requestxn#4]
Thanks for this module. 

Besides returning 5xx codes, there are other cases in which you might want to retry a request:

 * HTTP status code 429 means "Too Many Requests" and is used when API providers are throttling. 
 * ECONNRESET, ECONNREFUSED, ETIMEOUT are all types of errors that can be returned even before a server responds, so no HTTP status code may be set. ( I haven't looked at how `request-promise` handles these internally ).

**Comment by kobik** [comment]
Hi @markstos,

Thanks for your feedback.

Retries on network issues are currently supported by default when setting `max` to a value greater than 1.
I'll add a flag for using retries on Too Many Connections.

**Comment by markstos** [comment]
@kobik I missed that `retryStrategy` already supports defining custom logic, which is all I need.  

This issue can be closed, unless you want add built-in support for 429 errors.

Great module! I appreciate the good documentation.

**Comment by kobik** [comment]
Closing this issue as it's currently supported using retryStrategy
